/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cvrp_CONSTANTS_H
#define cvrp_CONSTANTS_H

#include "cvrp_types.h"



class cvrpConstants {
 public:
  cvrpConstants();

};

extern const cvrpConstants g_cvrp_constants;



#endif
