/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cvrp_constants.h"



const cvrpConstants g_cvrp_constants;

cvrpConstants::cvrpConstants() {
}



