/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cvrptw_model_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




CVRPTWData::~CVRPTWData() throw() {
}


void CVRPTWData::__set_vec(const std::vector<std::vector<int64_t> > & val) {
  this->vec = val;
}

void CVRPTWData::__set_demands(const std::vector<int64_t> & val) {
  this->demands = val;
}

void CVRPTWData::__set_v_caps(const std::vector<int64_t> & val) {
  this->v_caps = val;
}

void CVRPTWData::__set_timeWindows(const std::vector<std::vector<int64_t> > & val) {
  this->timeWindows = val;
}

void CVRPTWData::__set_serviceTime(const std::vector<int64_t> & val) {
  this->serviceTime = val;
}

void CVRPTWData::__set_vehWindows(const std::vector<std::vector<int64_t> > & val) {
  this->vehWindows = val;
}

void CVRPTWData::__set_depots(const std::vector<std::vector<int64_t> > & val) {
  this->depots = val;
}

void CVRPTWData::__set_deliveries(const std::vector<int64_t> & val) {
  this->deliveries = val;
}

void CVRPTWData::__set_pickups(const std::vector<int64_t> & val) {
  this->pickups = val;
}

void CVRPTWData::__set_taskType(const std::string& val) {
  this->taskType = val;
}

uint32_t CVRPTWData::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->vec.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->vec.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              {
                this->vec[_i4].clear();
                uint32_t _size5;
                ::apache::thrift::protocol::TType _etype8;
                xfer += iprot->readListBegin(_etype8, _size5);
                this->vec[_i4].resize(_size5);
                uint32_t _i9;
                for (_i9 = 0; _i9 < _size5; ++_i9)
                {
                  xfer += iprot->readI64(this->vec[_i4][_i9]);
                }
                xfer += iprot->readListEnd();
              }
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.vec = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->demands.clear();
            uint32_t _size10;
            ::apache::thrift::protocol::TType _etype13;
            xfer += iprot->readListBegin(_etype13, _size10);
            this->demands.resize(_size10);
            uint32_t _i14;
            for (_i14 = 0; _i14 < _size10; ++_i14)
            {
              xfer += iprot->readI64(this->demands[_i14]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.demands = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->v_caps.clear();
            uint32_t _size15;
            ::apache::thrift::protocol::TType _etype18;
            xfer += iprot->readListBegin(_etype18, _size15);
            this->v_caps.resize(_size15);
            uint32_t _i19;
            for (_i19 = 0; _i19 < _size15; ++_i19)
            {
              xfer += iprot->readI64(this->v_caps[_i19]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.v_caps = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->timeWindows.clear();
            uint32_t _size20;
            ::apache::thrift::protocol::TType _etype23;
            xfer += iprot->readListBegin(_etype23, _size20);
            this->timeWindows.resize(_size20);
            uint32_t _i24;
            for (_i24 = 0; _i24 < _size20; ++_i24)
            {
              {
                this->timeWindows[_i24].clear();
                uint32_t _size25;
                ::apache::thrift::protocol::TType _etype28;
                xfer += iprot->readListBegin(_etype28, _size25);
                this->timeWindows[_i24].resize(_size25);
                uint32_t _i29;
                for (_i29 = 0; _i29 < _size25; ++_i29)
                {
                  xfer += iprot->readI64(this->timeWindows[_i24][_i29]);
                }
                xfer += iprot->readListEnd();
              }
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.timeWindows = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->serviceTime.clear();
            uint32_t _size30;
            ::apache::thrift::protocol::TType _etype33;
            xfer += iprot->readListBegin(_etype33, _size30);
            this->serviceTime.resize(_size30);
            uint32_t _i34;
            for (_i34 = 0; _i34 < _size30; ++_i34)
            {
              xfer += iprot->readI64(this->serviceTime[_i34]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.serviceTime = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->vehWindows.clear();
            uint32_t _size35;
            ::apache::thrift::protocol::TType _etype38;
            xfer += iprot->readListBegin(_etype38, _size35);
            this->vehWindows.resize(_size35);
            uint32_t _i39;
            for (_i39 = 0; _i39 < _size35; ++_i39)
            {
              {
                this->vehWindows[_i39].clear();
                uint32_t _size40;
                ::apache::thrift::protocol::TType _etype43;
                xfer += iprot->readListBegin(_etype43, _size40);
                this->vehWindows[_i39].resize(_size40);
                uint32_t _i44;
                for (_i44 = 0; _i44 < _size40; ++_i44)
                {
                  xfer += iprot->readI64(this->vehWindows[_i39][_i44]);
                }
                xfer += iprot->readListEnd();
              }
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.vehWindows = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->depots.clear();
            uint32_t _size45;
            ::apache::thrift::protocol::TType _etype48;
            xfer += iprot->readListBegin(_etype48, _size45);
            this->depots.resize(_size45);
            uint32_t _i49;
            for (_i49 = 0; _i49 < _size45; ++_i49)
            {
              {
                this->depots[_i49].clear();
                uint32_t _size50;
                ::apache::thrift::protocol::TType _etype53;
                xfer += iprot->readListBegin(_etype53, _size50);
                this->depots[_i49].resize(_size50);
                uint32_t _i54;
                for (_i54 = 0; _i54 < _size50; ++_i54)
                {
                  xfer += iprot->readI64(this->depots[_i49][_i54]);
                }
                xfer += iprot->readListEnd();
              }
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.depots = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->deliveries.clear();
            uint32_t _size55;
            ::apache::thrift::protocol::TType _etype58;
            xfer += iprot->readListBegin(_etype58, _size55);
            this->deliveries.resize(_size55);
            uint32_t _i59;
            for (_i59 = 0; _i59 < _size55; ++_i59)
            {
              xfer += iprot->readI64(this->deliveries[_i59]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.deliveries = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->pickups.clear();
            uint32_t _size60;
            ::apache::thrift::protocol::TType _etype63;
            xfer += iprot->readListBegin(_etype63, _size60);
            this->pickups.resize(_size60);
            uint32_t _i64;
            for (_i64 = 0; _i64 < _size60; ++_i64)
            {
              xfer += iprot->readI64(this->pickups[_i64]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.pickups = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->taskType);
          this->__isset.taskType = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CVRPTWData::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CVRPTWData");

  xfer += oprot->writeFieldBegin("vec", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_LIST, static_cast<uint32_t>(this->vec.size()));
    std::vector<std::vector<int64_t> > ::const_iterator _iter65;
    for (_iter65 = this->vec.begin(); _iter65 != this->vec.end(); ++_iter65)
    {
      {
        xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>((*_iter65).size()));
        std::vector<int64_t> ::const_iterator _iter66;
        for (_iter66 = (*_iter65).begin(); _iter66 != (*_iter65).end(); ++_iter66)
        {
          xfer += oprot->writeI64((*_iter66));
        }
        xfer += oprot->writeListEnd();
      }
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("demands", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->demands.size()));
    std::vector<int64_t> ::const_iterator _iter67;
    for (_iter67 = this->demands.begin(); _iter67 != this->demands.end(); ++_iter67)
    {
      xfer += oprot->writeI64((*_iter67));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("v_caps", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->v_caps.size()));
    std::vector<int64_t> ::const_iterator _iter68;
    for (_iter68 = this->v_caps.begin(); _iter68 != this->v_caps.end(); ++_iter68)
    {
      xfer += oprot->writeI64((*_iter68));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("timeWindows", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_LIST, static_cast<uint32_t>(this->timeWindows.size()));
    std::vector<std::vector<int64_t> > ::const_iterator _iter69;
    for (_iter69 = this->timeWindows.begin(); _iter69 != this->timeWindows.end(); ++_iter69)
    {
      {
        xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>((*_iter69).size()));
        std::vector<int64_t> ::const_iterator _iter70;
        for (_iter70 = (*_iter69).begin(); _iter70 != (*_iter69).end(); ++_iter70)
        {
          xfer += oprot->writeI64((*_iter70));
        }
        xfer += oprot->writeListEnd();
      }
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("serviceTime", ::apache::thrift::protocol::T_LIST, 5);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->serviceTime.size()));
    std::vector<int64_t> ::const_iterator _iter71;
    for (_iter71 = this->serviceTime.begin(); _iter71 != this->serviceTime.end(); ++_iter71)
    {
      xfer += oprot->writeI64((*_iter71));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("vehWindows", ::apache::thrift::protocol::T_LIST, 6);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_LIST, static_cast<uint32_t>(this->vehWindows.size()));
    std::vector<std::vector<int64_t> > ::const_iterator _iter72;
    for (_iter72 = this->vehWindows.begin(); _iter72 != this->vehWindows.end(); ++_iter72)
    {
      {
        xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>((*_iter72).size()));
        std::vector<int64_t> ::const_iterator _iter73;
        for (_iter73 = (*_iter72).begin(); _iter73 != (*_iter72).end(); ++_iter73)
        {
          xfer += oprot->writeI64((*_iter73));
        }
        xfer += oprot->writeListEnd();
      }
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("depots", ::apache::thrift::protocol::T_LIST, 7);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_LIST, static_cast<uint32_t>(this->depots.size()));
    std::vector<std::vector<int64_t> > ::const_iterator _iter74;
    for (_iter74 = this->depots.begin(); _iter74 != this->depots.end(); ++_iter74)
    {
      {
        xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>((*_iter74).size()));
        std::vector<int64_t> ::const_iterator _iter75;
        for (_iter75 = (*_iter74).begin(); _iter75 != (*_iter74).end(); ++_iter75)
        {
          xfer += oprot->writeI64((*_iter75));
        }
        xfer += oprot->writeListEnd();
      }
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("deliveries", ::apache::thrift::protocol::T_LIST, 8);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->deliveries.size()));
    std::vector<int64_t> ::const_iterator _iter76;
    for (_iter76 = this->deliveries.begin(); _iter76 != this->deliveries.end(); ++_iter76)
    {
      xfer += oprot->writeI64((*_iter76));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pickups", ::apache::thrift::protocol::T_LIST, 9);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->pickups.size()));
    std::vector<int64_t> ::const_iterator _iter77;
    for (_iter77 = this->pickups.begin(); _iter77 != this->pickups.end(); ++_iter77)
    {
      xfer += oprot->writeI64((*_iter77));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("taskType", ::apache::thrift::protocol::T_STRING, 10);
  xfer += oprot->writeString(this->taskType);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CVRPTWData &a, CVRPTWData &b) {
  using ::std::swap;
  swap(a.vec, b.vec);
  swap(a.demands, b.demands);
  swap(a.v_caps, b.v_caps);
  swap(a.timeWindows, b.timeWindows);
  swap(a.serviceTime, b.serviceTime);
  swap(a.vehWindows, b.vehWindows);
  swap(a.depots, b.depots);
  swap(a.deliveries, b.deliveries);
  swap(a.pickups, b.pickups);
  swap(a.taskType, b.taskType);
  swap(a.__isset, b.__isset);
}

CVRPTWData::CVRPTWData(const CVRPTWData& other78) {
  vec = other78.vec;
  demands = other78.demands;
  v_caps = other78.v_caps;
  timeWindows = other78.timeWindows;
  serviceTime = other78.serviceTime;
  vehWindows = other78.vehWindows;
  depots = other78.depots;
  deliveries = other78.deliveries;
  pickups = other78.pickups;
  taskType = other78.taskType;
  __isset = other78.__isset;
}
CVRPTWData& CVRPTWData::operator=(const CVRPTWData& other79) {
  vec = other79.vec;
  demands = other79.demands;
  v_caps = other79.v_caps;
  timeWindows = other79.timeWindows;
  serviceTime = other79.serviceTime;
  vehWindows = other79.vehWindows;
  depots = other79.depots;
  deliveries = other79.deliveries;
  pickups = other79.pickups;
  taskType = other79.taskType;
  __isset = other79.__isset;
  return *this;
}
void CVRPTWData::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CVRPTWData(";
  out << "vec=" << to_string(vec);
  out << ", " << "demands=" << to_string(demands);
  out << ", " << "v_caps=" << to_string(v_caps);
  out << ", " << "timeWindows=" << to_string(timeWindows);
  out << ", " << "serviceTime=" << to_string(serviceTime);
  out << ", " << "vehWindows=" << to_string(vehWindows);
  out << ", " << "depots=" << to_string(depots);
  out << ", " << "deliveries=" << to_string(deliveries);
  out << ", " << "pickups=" << to_string(pickups);
  out << ", " << "taskType=" << to_string(taskType);
  out << ")";
}


Result::~Result() throw() {
}


void Result::__set_result(const std::vector<std::vector<int64_t> > & val) {
  this->result = val;
}

uint32_t Result::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->result.clear();
            uint32_t _size80;
            ::apache::thrift::protocol::TType _etype83;
            xfer += iprot->readListBegin(_etype83, _size80);
            this->result.resize(_size80);
            uint32_t _i84;
            for (_i84 = 0; _i84 < _size80; ++_i84)
            {
              {
                this->result[_i84].clear();
                uint32_t _size85;
                ::apache::thrift::protocol::TType _etype88;
                xfer += iprot->readListBegin(_etype88, _size85);
                this->result[_i84].resize(_size85);
                uint32_t _i89;
                for (_i89 = 0; _i89 < _size85; ++_i89)
                {
                  xfer += iprot->readI64(this->result[_i84][_i89]);
                }
                xfer += iprot->readListEnd();
              }
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.result = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Result::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Result");

  xfer += oprot->writeFieldBegin("result", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_LIST, static_cast<uint32_t>(this->result.size()));
    std::vector<std::vector<int64_t> > ::const_iterator _iter90;
    for (_iter90 = this->result.begin(); _iter90 != this->result.end(); ++_iter90)
    {
      {
        xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>((*_iter90).size()));
        std::vector<int64_t> ::const_iterator _iter91;
        for (_iter91 = (*_iter90).begin(); _iter91 != (*_iter90).end(); ++_iter91)
        {
          xfer += oprot->writeI64((*_iter91));
        }
        xfer += oprot->writeListEnd();
      }
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Result &a, Result &b) {
  using ::std::swap;
  swap(a.result, b.result);
  swap(a.__isset, b.__isset);
}

Result::Result(const Result& other92) {
  result = other92.result;
  __isset = other92.__isset;
}
Result& Result::operator=(const Result& other93) {
  result = other93.result;
  __isset = other93.__isset;
  return *this;
}
void Result::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Result(";
  out << "result=" << to_string(result);
  out << ")";
}


