/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cvrptw_model_CONSTANTS_H
#define cvrptw_model_CONSTANTS_H

#include "cvrptw_model_types.h"



class cvrptw_modelConstants {
 public:
  cvrptw_modelConstants();

};

extern const cvrptw_modelConstants g_cvrptw_model_constants;



#endif
