/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cvrptw_model_constants.h"



const cvrptw_modelConstants g_cvrptw_model_constants;

cvrptw_modelConstants::cvrptw_modelConstants() {
}



